name: remedius_mobile
description: RemediusLive MVP mobile app
publish_to: "none"
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3
  dio: ^5.5.0
  flutter_webrtc: ^0.11.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.1.2
  go_router: ^14.2.0
  riverpod: ^2.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
